services:
  api.web:
    image: ${DOCKER_REGISTRY-}apiweb
    build:
      context: .
      dockerfile: Api.Web/Dockerfile
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "80:80"
    volumes:
      - seq-data:/data


volumes:
  seq-data:
